python GeneticAlgorithmDriver.py > ./logs/log0.txt & 
python GeneticAlgorithmDriver.py > ./logs/log1.txt & 
python GeneticAlgorithmDriver.py > ./logs/log2.txt & 
python GeneticAlgorithmDriver.py > ./logs/log3.txt & 
python GeneticAlgorithmDriver.py > ./logs/log4.txt & 
python GeneticAlgorithmDriver.py > ./logs/log5.txt & 
python GeneticAlgorithmDriver.py > ./logs/log6.txt & 
python GeneticAlgorithmDriver.py > ./logs/log7.txt & 
python GeneticAlgorithmDriver.py > ./logs/log8.txt & 
python GeneticAlgorithmDriver.py > ./logs/log9.txt & 
python GeneticAlgorithmDriver.py > ./logs/log10.txt & 
python GeneticAlgorithmDriver.py > ./logs/log11.txt & 
python GeneticAlgorithmDriver.py > ./logs/log12.txt & 
python GeneticAlgorithmDriver.py > ./logs/log13.txt & 
python GeneticAlgorithmDriver.py > ./logs/log14.txt & 
python GeneticAlgorithmDriver.py > ./logs/log15.txt & 
python GeneticAlgorithmDriver.py > ./logs/log16.txt & 
python GeneticAlgorithmDriver.py > ./logs/log17.txt & 
python GeneticAlgorithmDriver.py > ./logs/log18.txt & 
python GeneticAlgorithmDriver.py > ./logs/log19.txt & 
python GeneticAlgorithmDriver.py > ./logs/log20.txt & 
python GeneticAlgorithmDriver.py > ./logs/log21.txt & 
python GeneticAlgorithmDriver.py > ./logs/log22.txt & 
python GeneticAlgorithmDriver.py > ./logs/log23.txt & 
python GeneticAlgorithmDriver.py > ./logs/log24.txt & 
python GeneticAlgorithmDriver.py > ./logs/log25.txt & 
python GeneticAlgorithmDriver.py > ./logs/log26.txt & 
python GeneticAlgorithmDriver.py > ./logs/log27.txt & 
python GeneticAlgorithmDriver.py > ./logs/log28.txt & 
python GeneticAlgorithmDriver.py > ./logs/log29.txt & 
python GeneticAlgorithmDriver.py > ./logs/log30.txt & 
python GeneticAlgorithmDriver.py > ./logs/log31.txt & 
python GeneticAlgorithmDriver.py > ./logs/log32.txt & 
python GeneticAlgorithmDriver.py > ./logs/log33.txt & 
python GeneticAlgorithmDriver.py > ./logs/log34.txt & 
python GeneticAlgorithmDriver.py > ./logs/log35.txt & 
python GeneticAlgorithmDriver.py > ./logs/log36.txt & 
python GeneticAlgorithmDriver.py > ./logs/log37.txt & 
python GeneticAlgorithmDriver.py > ./logs/log38.txt & 
python GeneticAlgorithmDriver.py > ./logs/log39.txt & 
python GeneticAlgorithmDriver.py > ./logs/log40.txt & 
python GeneticAlgorithmDriver.py > ./logs/log41.txt & 
python GeneticAlgorithmDriver.py > ./logs/log42.txt & 
python GeneticAlgorithmDriver.py > ./logs/log43.txt & 
python GeneticAlgorithmDriver.py > ./logs/log44.txt & 
python GeneticAlgorithmDriver.py > ./logs/log45.txt & 
python GeneticAlgorithmDriver.py > ./logs/log46.txt & 
python GeneticAlgorithmDriver.py > ./logs/log47.txt & 
python GeneticAlgorithmDriver.py > ./logs/log48.txt & 
python GeneticAlgorithmDriver.py > ./logs/log49.txt & 
python GeneticAlgorithmDriver.py > ./logs/log50.txt & 
python GeneticAlgorithmDriver.py > ./logs/log51.txt & 
python GeneticAlgorithmDriver.py > ./logs/log52.txt & 
python GeneticAlgorithmDriver.py > ./logs/log53.txt & 
python GeneticAlgorithmDriver.py > ./logs/log54.txt & 
python GeneticAlgorithmDriver.py > ./logs/log55.txt & 
python GeneticAlgorithmDriver.py > ./logs/log56.txt & 
python GeneticAlgorithmDriver.py > ./logs/log57.txt & 
python GeneticAlgorithmDriver.py > ./logs/log58.txt & 
python GeneticAlgorithmDriver.py > ./logs/log59.txt & 
python GeneticAlgorithmDriver.py > ./logs/log60.txt & 
python GeneticAlgorithmDriver.py > ./logs/log61.txt & 
python GeneticAlgorithmDriver.py > ./logs/log62.txt & 
python GeneticAlgorithmDriver.py > ./logs/log63.txt & 
python GeneticAlgorithmDriver.py > ./logs/log64.txt & 
python GeneticAlgorithmDriver.py > ./logs/log65.txt & 
python GeneticAlgorithmDriver.py > ./logs/log66.txt & 
python GeneticAlgorithmDriver.py > ./logs/log67.txt & 
python GeneticAlgorithmDriver.py > ./logs/log68.txt & 
python GeneticAlgorithmDriver.py > ./logs/log69.txt & 
python GeneticAlgorithmDriver.py > ./logs/log70.txt & 
python GeneticAlgorithmDriver.py > ./logs/log71.txt & 
python GeneticAlgorithmDriver.py > ./logs/log72.txt & 
python GeneticAlgorithmDriver.py > ./logs/log73.txt & 
python GeneticAlgorithmDriver.py > ./logs/log74.txt & 
python GeneticAlgorithmDriver.py > ./logs/log75.txt & 
python GeneticAlgorithmDriver.py > ./logs/log76.txt & 
python GeneticAlgorithmDriver.py > ./logs/log77.txt & 
python GeneticAlgorithmDriver.py > ./logs/log78.txt & 
python GeneticAlgorithmDriver.py > ./logs/log79.txt & 
python GeneticAlgorithmDriver.py > ./logs/log80.txt & 
python GeneticAlgorithmDriver.py > ./logs/log81.txt & 
python GeneticAlgorithmDriver.py > ./logs/log82.txt & 
python GeneticAlgorithmDriver.py > ./logs/log83.txt & 
python GeneticAlgorithmDriver.py > ./logs/log84.txt & 
python GeneticAlgorithmDriver.py > ./logs/log85.txt & 
python GeneticAlgorithmDriver.py > ./logs/log86.txt & 
python GeneticAlgorithmDriver.py > ./logs/log87.txt & 
python GeneticAlgorithmDriver.py > ./logs/log88.txt & 
python GeneticAlgorithmDriver.py > ./logs/log89.txt & 
python GeneticAlgorithmDriver.py > ./logs/log90.txt & 
python GeneticAlgorithmDriver.py > ./logs/log91.txt & 
python GeneticAlgorithmDriver.py > ./logs/log92.txt & 
python GeneticAlgorithmDriver.py > ./logs/log93.txt & 
python GeneticAlgorithmDriver.py > ./logs/log94.txt & 
python GeneticAlgorithmDriver.py > ./logs/log95.txt & 
python GeneticAlgorithmDriver.py > ./logs/log96.txt & 
python GeneticAlgorithmDriver.py > ./logs/log97.txt & 
python GeneticAlgorithmDriver.py > ./logs/log98.txt & 
python GeneticAlgorithmDriver.py > ./logs/log99.txt